name: Hello World

on: [push]

jobs:
  build:
    name: Greet
    runs_on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Run a one-line script
      run: echo Hello, world! It worked again!